# -*- coding: utf-8 -*-
"""Chuong 1 - Lap ke hoach cho du an."""

CHUONG_1 = [
    ("h1", "CHƯƠNG 1. LẬP KẾ HOẠCH CHO DỰ ÁN"),

    ("h2", "1.1. Tổng quan dự án"),

    ("h3", "1.1.1. Thông tin chung về dự án"),
    ("p", "Bảng 1.1 tóm tắt các thông tin định danh của dự án. Mỗi dòng kèm cột nguồn xác minh, vì một thông tin chỉ có giá trị khi biết nó đến từ đâu."),
    ("tbl", "Bảng 1.1. Thông tin chung về dự án",
     ["Hạng mục", "Nội dung", "Nguồn xác minh"],
     [
        ["Tên dự án", "Personal Finance AI System (Hệ thống quản lý chi tiêu cá nhân có trợ lý AI)", "README.md, backend/pom.xml, admin-web/package.json"],
        ["Mã định danh", "finai", "Tên gói Java, tên container"],
        ["Mục đích", "Quản lý tài chính cá nhân kèm phân tích AI có ràng buộc dữ liệu thực", "Mục tiêu dự án"],
        ["Kho mã nguồn", "https://github.com/HoangKhai1612/expense_management.git", "Cấu hình Git remote"],
        ["Nhánh phát triển", "main", "Lệnh git branch"],
        ["Thẻ phát hành", "v1.0.0-academic-final", "Lệnh git tag"],
        ["Số tệp trong baseline", "232", "git ls-tree -r HEAD"],
        ["Ngày kiểm chứng cuối", "02/10/2026", "Nhật ký kiểm thử"],
     ], [3.5, 7.5, 4.0]),
    ("p", "Dự án được xây dựng với ba thành phần tương tác: một ứng dụng Android cho người dùng cuối, một bảng điều khiển web cho quản trị viên, và một dịch vụ backend trung tâm đảm bảo tính nhất quán dữ liệu. Ba thành phần này không chia sẻ cơ sở dữ liệu trực tiếp mà đều đi qua backend, nhờ vậy quy tắc kiểm soát truy cập được áp dụng tập trung tại một điểm."),

    ("h3", "1.1.2. Kiến trúc tổng thể"),
    ("p", "Kiến trúc hệ thống được tổ chức thành ba tầng: tầng trình bày, tầng ứng dụng và tầng dữ liệu. Hình 1.1 trình bày cấu trúc ba tầng cùng đường đi của dữ liệu. Điểm đáng chú ý về mặt quản lý là ranh giới giữa các tầng được giữ ở dạng hợp đồng, không phải ở dạng chia sẻ cơ sở dữ liệu: hai ứng dụng đều chỉ giao tiếp với backend qua giao diện lập trình, nên một quy tắc kiểm soát truy cập được áp dụng cho toàn bộ người dùng thay vì phải lặp lại ở từng ứng dụng."),
    ("fig", "report/figures/01_kien_truc_he_thong.png", "Hình 1.1. Kiến trúc ba tầng của hệ thống quản lý chi tiêu cá nhân kèm đường đi dữ liệu"),
    ("p", "Ranh giới tầng cũng quyết định phạm vi kiểm thử: lớp nghiệp vụ chỉ nhận dữ liệu đã được kiểm tra, nhờ vậy 113 kiểm thử đơn vị của backend tập trung được vào quy tắc nghiệp vụ mà không cần dựng hạ tầng phụ. Đây là lý do bộ kiểm thử backend có thể chạy trong thời gian ngắn và được đưa vào đường dẫn kiểm chứng tự động."),

    ("h3", "1.1.3. Mục tiêu dự án"),
    ("p", "Mục tiêu dự án được xác định từ bài toán nghiệp vụ, không phải từ danh sách tính năng. Bảng 1.2 trình bày bốn mục tiêu kèm tiêu chí kiểm chứng tương ứng. Cách đặt mục tiêu này phù hợp với nguyên tắc trong hướng dẫn của Viện Quản lý Dự án, theo đó kết quả bàn giao phải gắn với mục tiêu kinh doanh và nhu cầu của các bên liên quan [1]."),
    ("tbl", "Bảng 1.2. Mục tiêu dự án và tiêu chí kiểm chứng",
     ["Mã", "Mục tiêu", "Tiêu chí kiểm chứng"],
     [
        ["M1", "Quản lý chi tiêu đầy đủ chức năng", "Giao dịch, danh mục, ngân sách, thông báo đều có kiểm thử tự động"],
        ["M2", "Phân tích AI có căn cứ dữ liệu thực", "Mỗi ý định phân tích kiểm chứng giá trị; từ chối khi thiếu dữ liệu"],
        ["M3", "Bảng điều khiển quản trị hoàn chỉnh", "Bộ kiểm thử hợp đồng API đạt 102/102"],
        ["M4", "Tái lập được và kiểm chứng được", "Triển khai bằng một lệnh; 5 bộ kiểm thử chạy lại được"],
     ], [1.5, 6.5, 7.0]),

    ("h3", "1.1.4. Phạm vi dự án"),
    ("h4", "1.1.4.1. Phạm vi trong dự án"),
    ("p", "Phạm vi trong dự án được xác định bằng chức năng cụ thể, mỗi chức năng gắn với nhóm kiểm thử tương ứng để chứng minh rằng phạm vi đã được thực hiện chứ không chỉ được tuyên bố."),
    ("tbl", "Bảng 1.3. Phạm vi chức năng trong dự án",
     ["Nhóm", "Chức năng", "Bằng chứng thực thi"],
     [
        ["Xác thực", "Đăng ký, đăng nhập, quản lý phiên đăng nhập, khóa tài khoản", "AuthServiceTest: 11 kiểm thử"],
        ["Người dùng", "Hồ sơ cá nhân, đổi trạng thái tài khoản, phân quyền theo vai trò", "E2E: các ca 403 và 404"],
        ["Danh mục", "Tạo, sửa, vô hiệu hóa danh mục thu chi", "CategoryServiceTest: 13 kiểm thử"],
        ["Giao dịch", "Ghi nhận thu chi, lọc theo kỳ và danh mục, phân trang", "TransactionServiceTest: 19 kiểm thử"],
        ["Ngân sách", "Đặt hạn mức theo kỳ, cảnh báo khi vượt ngưỡng", "BudgetServiceTest: 15 kiểm thử"],
        ["Thông báo", "Sinh thông báo tự động theo ngưỡng ngân sách", "E2E: cảnh báo chỉ nổi một lần"],
        ["AI phân tích", "Sáu ý định phân tích, trả lời bằng tiếng Việt", "AiTextTest: 24, AiGroundingIT: 8"],
        ["Phản hồi", "Gửi phản hồi qua API, tiếp nhận trong bảng quản trị", "Hợp đồng API quản trị"],
        ["Kiểm toán", "Ghi nhận ký hành động quản trị", "Có bảng audit_logs, 11 bảng tổng"],
        ["Bảng quản trị", "Quản lý người dùng, danh mục, phản hồi, nhật ký", "Kiểm thử hợp đồng: 102/102"],
     ], [3.0, 6.0, 6.0]),

    ("h4", "1.1.4.2. Phạm vi ngoài dự án"),
    ("p", "Những nội dung dưới đây không nằm trong phạm vi thực hiện. Mỗi mục được ghi nhận trong ma trận truy vết với trạng thái riêng, phân biệt giữa “chưa thực hiện” và “cố ý loại khỏi phạm vi”. Sự phân biệt này quan trọng vì loại trừ có chủ đích là quyết định phạm vi, còn thiếu sót là khoảng trống cần báo cáo."),
    ("tbl", "Bảng 1.4. Nội dung ngoài phạm vi dự án",
     ["Nội dung", "Lý do loại khỏi phạm vi"],
     [
        ["Giao diện gửi phản hồi trên ứng dụng di động", "Người dùng gửi phản hồi qua API và tiếp nhận trong bảng quản trị; giao diện di động không nằm trong phạm vi học thuật"],
        ["Kiểm thử tự động giao diện người dùng", "Bộ kiểm thử hợp đồng API đã kiểm soát lớp dữ liệu mà giao diện tiêu thụ"],
        ["Kiểm thử tải và hiệu năng", "Hệ thống phục vụ phạm vi học thuật, chưa có yêu cầu về quy mô tải"],
        ["Kiểm thử xâm nhập và quét mã độc hình thức", "Ngoài khả năng của môi trường dự án; đã thay bằng quét bí mật và rà soát nhật ký"],
        ["Hạ tầng triển khai phân tán", "Dự án cấu hình Docker Compose cho ba container, đủ cho phạm vi"],
     ], [6.0, 9.0]),

    ("h3", "1.1.5. Các bên liên quan"),
    ("p", "Danh sách các bên liên quan nhận biết được cùng mức độ quan tâm và ảnh hưởng được trình bày tại bảng 1.5. Danh sách này được lập từ vai trò thực tế trong hệ thống chứ không từ giả định về đội ngũ phát triển, vì dự án không có dữ liệu về thành phần nhân sự."),
    ("tbl", "Bảng 1.5. Ma trận bên liên quan",
     ["Bên liên quan", "Vai trò", "Mức ảnh hưởng", "Mức quan tâm", "Cách tham gia"],
     [
        ["Người dùng cuối", "Ghi nhận giao dịch, xem phân tích", "Thấp", "Cao", "Ứng dụng Android"],
        ["Quản trị viên", "Quản lý người dùng, danh mục, phản hồi", "Cao", "Cao", "Bảng điều khiển web"],
        ["Nhóm phát triển", "Xây dựng và bảo trì", "Cao", "Cao", "Mã nguồn, kiểm thử"],
        ["Người đánh giá học thuật", "Kiểm tra tính đầy đủ và khả kiểm chứng", "Cao", "Cao", "Ma trận truy vết, tài liệu"],
        ["Bộ phận vận hành", "Triển khai và giám sát hệ thống", "Trung bình", "Thấp", "Cấu hình Compose, tài liệu triển khai"],
     ], [3.2, 3.8, 2.2, 2.0, 3.8]),
    ("p", "Hai bên liên quan có ảnh hưởng cao là quản trị viên và người đánh giá học thuật. Đối với quản trị viên, yêu cầu cụ thể nhất là khả năng phân loại và xử lý phản hồi; đối với người đánh giá, yêu cầu là mọi tuyên bố phải truy ngược được về bằng chứng. Hai yêu cầu này định hình phần lớn quyết định thiết kế của hệ thống kiểm thử."),

    ("h3", "1.1.6. Sản phẩm bàn giao"),
    ("tbl", "Bảng 1.6. Sản phẩm bàn giao của dự án",
     ["Sản phẩm", "Nội dung", "Cách xác minh"],
     [
        ["Mã nguồn backend", "78 tệp Java, Spring Boot 3.5.16", "Đếm tệp trong backend/src/main/java"],
        ["Mã nguồn ứng dụng di động", "22 tệp Kotlin, kiến trúc MVVM", "Đếm tệp trong android/app/src/main/java"],
        ["Mã nguồn bảng quản trị", "13 tệp TypeScript và React", "Đếm tệp trong admin-web/src"],
        ["Cơ sở dữ liệu", "9 tệp migration Flyway, 11 bảng", "Bảng flyway_schema_history trong CSDL"],
        ["Cấu hình triển khai", "3 hình ảnh Docker, tệp Compose", "docker compose config"],
        ["Bộ kiểm thử", "5 bộ kiểm thử tự động, 385 kiểm tra", "Nhật ký kiểm thử cuối"],
        ["Tài liệu", "28 tệp Markdown", "Đếm tệp trong docs/"],
        ["Thẻ phát hành", "v1.0.0-academic-final", "git tag"],
     ], [3.5, 6.0, 5.5]),

    ("h2", "1.2. Cơ sở hạ tầng để lập kế hoạch"),

    ("h3", "1.2.1. Hạ tầng phần cứng"),
    ("p", "Dự án được kiểm thử trên hệ điều hành Windows 11 phiên bản 10.0 build 19045, kiến trúc amd64. Yêu cầu phần cứng phát sinh chủ yếu từ việc chạy đồng thời ba container, trong đó có ảnh nền PostgreSQL và hai ứng dụng JavaScript. Bộ nhớ đệm 8 GB trở lên là mức tối thiểu thực tế; dưới mức này quá trình khởi động stack sẽ chậm đáng kể do phải nạp lại tầng ứng dụng Java."),
    ("p", "Việc xây dựng ứng dụng di động cần thêm một thiết bị hoặc trình giả lập Android. Dự án sử dụng trình giả lập, và một ràng buộc vận hành đáng lưu ý là trình giả lập không phân giải được tên máy chủ localhost của máy tính; khi kết nối tới backend trên máy chủ, ứng dụng phải dùng địa chỉ 10.0.2.2. Đây không phải lỗi cấu hình mà là đặc thù kiến trúc của trình giả lập."),

    ("h3", "1.2.2. Hạ tầng phần mềm"),
    ("p", "Toàn bộ công nghệ sử dụng kèm phiên bản cụ thể được liệt kê tại bảng 1.7. Việc ghi rõ phiên bản không phải thói quen hình thức: mỗi mức phiên bản trong bảng này thay đổi hành vi thực tế. Chẳng hạn, Spring Boot 3.5.16 yêu cầu Java từ 17 trở lên và tương thích tới Java 25 theo tài liệu chính thức [8], trong khi dự án dùng Java 21 cho backend và JDK 25 riêng cho phần Android."),
    ("tbl", "Bảng 1.7. Công nghệ sử dụng trong dự án",
     ["Thành phần", "Công nghệ", "Phiên bản", "Vai trò"],
     [
        ["Backend", "Spring Boot", "3.5.16", "Khung ứng dụng, tiêu chuẩn do [8]"],
        ["Ngôn ngữ backend", "Java", "21", "Ngôn ngữ lập trình"],
        ["Cơ sở dữ liệu", "PostgreSQL", "16-alpine", "Lưu trữ dữ liệu, tài liệu [13]"],
        ["Quản lý phiên bản CSDL", "Flyway", "Đi kèm Spring Boot", "9 migration có mã bam kiểm tra [10]"],
        ["Ứng dụng di động", "Kotlin, Jetpack Compose", "Gradle 9.6.0", "Giao diện theo khuyến nghị kiến trúc [11]"],
        ["Bảng quản trị", "React, TypeScript, Vite", "Node 22", "Ứng dụng một trang"],
        ["Máy chủ web", "Nginx", "1.27-alpine", "Phục vụ tệp tĩnh và chuyển tiếp API"],
        ["Trợ lý xác thực", "JJWT 0.12.6", "Đi kèm", "Ký và kiểm tra token theo [12]"],
        ["Kiểm thử", "JUnit 5, PowerShell", "—", "5 bộ kiểm thử tự động"],
        ["Công cụ đóng gói", "Docker Compose", "—", "Định nghĩa ứng dụng đa container theo [9]"],
     ], [3.0, 3.5, 2.8, 5.7]),

    ("h3", "1.2.3. Môi trường phát triển"),
    ("p", "Môi trường phát triển tách bạch thông qua cấu hình biến môi trường, mọi giá trị nhạy cảm đều đọc từ tệp .env chứ không ghi thẳng vào mã nguồn. Tệp .env bị loại trừ khỏi quản lý phiên bản, và dự án xác nhận không có bí mật nào được ghi vào kho mã nguồn. Điều này được kiểm chứng bằng quét trước khi ghi thay đổi, cho kết quả 0 bí mật."),
    ("p", "Các cổng dịch vụ được dời khỏi giá trị mặc định để tránh xung đột với dịch vụ đang chạy sẵn trên máy phát triển: PostgreSQL dùng cổng 5433 thay vì 5432, backend dùng 8081, bảng quản trị dùng 5173. Cách dời cổng này cho phép chạy stack của dự án song song với PostgreSQL cài sẵn mà không xung đột."),

    ("h3", "1.2.4. Công cụ quản lý và hỗ trợ dự án"),
    ("p", "Bảng 1.8 liệt kê các công cụ đã dùng, kèm mục đích sử dụng. Điểm đáng chú ý là mọi công cụ trong bảng đều là công cụ có sẵn hoặc miễn phí, không có công cụ trả phí nào trong danh sách."),
    ("tbl", "Bảng 1.8. Công cụ sử dụng theo mục đích",
     ["Mục đích", "Công cụ", "Cách dùng trong dự án"],
     [
        ["Quản lý mã nguồn", "Git", "Theo dõi thay đổi, đánh dấu phát hành theo [14]"],
        ["Xây dựng backend", "Maven", "Đóng gói và chạy kiểm thử tự động"],
        ["Xây dựng di động", "Gradle", "Biên dịch và kiểm thử đơn vị"],
        ["Xây dựng giao diện", "npm, Vite", "Kiểm tra kiểu và đóng gói"],
        ["Đóng gói và chạy", "Docker Compose", "Ba container, kiểm tra sức khoẻ tự động"],
        ["Rà soát bảo mật", "npm audit, rà soát thủ công", "Soát phụ thuộc và nội dung nhật ký"],
        ["Mô tả sơ đồ", "Mermaid", "Sinh sơ đồ đơn sắc cho báo cáo"],
     ], [3.5, 3.5, 8.0]),

    ("h2", "1.3. Lập kế hoạch cho quy trình"),

    ("h3", "1.3.1. Mô hình và quy trình phát triển"),
    ("p", "Dự án không áp dụng một mô hình phát triển nào theo lý thuyết một cách cứng nhắc. Quy trình thực tế là mô hình lặp theo giai đoạn, trong đó mỗi giai đoạn kết thúc bằng một điều kiện kiểm chứng cụ thể trước khi chuyển sang giai đoạn kế tiếp. Tiêu chuẩn vòng đời phần mềm quốc tế mô tả các quy trình có thể được áp dụng đồng thời, lặp lại và đệ quy trong suốt vòng đời [4]; dự án cắt lược mô hình đó thành bốn giai đoạn cụ thể phù hợp với quy mô và bối cảnh của mình."),
    ("p", "Lựa chọn này phù hợp với nguyên tắc điều chỉnh mô hình trong hướng dẫn của Viện Quản lý Dự án, theo đó cách tiếp cận phát triển phải được chọn và điều chỉnh theo bối cảnh dự án [1]. Dự án có quy mô một nhóm nhỏ, yêu cầu nghiệp vụ rõ ràng, và không có ràng buộc phụ thuộc lẫn nhau giữa các thành phần theo chu kỳ thời gian. Với bối cảnh đó, mô hình giai đoạn đơn giản cho phép kiểm chứng rõ ràng hơn so với quy trình lặp nhanh với nhiều chu kỳ thời gian ngắn."),
    ("fig", "report/figures/02_vong_doi_du_an.png", "Hình 1.2. Chu trình quản lý dự án của hệ thống quản lý chi tiêu cá nhân"),
    ("p", "Hình 1.2 thể hiện vòng đời dự án gồm bốn giai đoạn: lập kế hoạch, thực hiện, kiểm soát và kết thúc. Điểm đáng chú ý trong sơ đồ là mũi tên phản hồi từ giai đoạn kiểm soát trở lại giai đoạn lập kế hoạch. Mũi tên này không mang tính hình thức: trong quá trình kiểm toán cuối, dự án phát hiện tám sai lệch giữa tài liệu và thực tế, và bốn sai lệch trong số đó dẫn tới việc phải sửa lại chính tài liệu kế hoạch. Cơ chế phản hồi này hoạt động và đã được sử dụng có hiệu quả."),

    ("h3", "1.3.2. Các giai đoạn thực hiện"),
    ("tbl", "Bảng 1.9. Bốn giai đoạn của dự án",
     ["Giai đoạn", "Nội dung chính", "Điều kiện kết thúc"],
     [
        ["1. Lập kế hoạch", "Xác định phạm vi, chọn công nghệ, lập sổ rủi ro, xác định tiêu chí nghiệm thu", "Danh mục chức năng và sổ rủi ro có nội dung"],
        ["2. Thực hiện", "Xây dựng backend, ứng dụng di động, bảng quản trị, CSDL, mô-đun AI", "Mã nguồn biên dịch được, migration áp dụng được"],
        ["3. Kiểm soát", "Kiểm thử, giám sát, quản lý lỗi, rà soát tài liệu", "5 bộ kiểm thử chạy, 0 lỗi"],
        ["4. Kết thúc", "Đánh giá mức độ hoàn thành, bàn giao, xác lập baseline, tuyên bố", "Thẻ phát hành được tạo"],
     ], [2.5, 6.0, 6.5]),

    ("h3", "1.3.3. Hoạt động của từng giai đoạn"),
    ("p", "Giai đoạn lập kế hoạch tập trung vào việc biến yêu cầu nghiệp vụ thành danh mục chức năng có thể kiểm thử. Hoạt động quan trọng nhất của giai đoạn này là xác định tiêu chí nghiệm thu trước khi viết mã, vì tiêu chí này trở thành cơ sở để đánh giá công bằng ở giai đoạn cuối."),
    ("p", "Giai đoạn thực hiện được tổ chức theo thành phần, cho phép kiểm thử từng phần độc lập. Một quyết định thiết kế đáng lưu ý là mô-đun AI không sinh câu trả lời trực tiếp từ mô hình ngôn ngữ, mà chỉ chọn lựa chọn trong tập dữ liệu đã tính sẵn rồi định dạng thành văn bản. Quyết định này biến bài toán từ “làm cho AI đúng” thành “bảo đảm AI không sai”, vốn là bài toán có lời giải kiểm chứng được bằng kiểm thử."),
    ("p", "Giai đoạn kiểm soát diễn ra liên tục chứ không phải ở cuối. Bộ kiểm thử hợp đồng API được viết song song với bảng quản trị, và bộ kiểm thử E2E được viết trước khi chạy hệ thống lần đầu. Cách tổ chức này cho phép phát hiện sai lệch sớm, khi chi phí sửa còn thấp."),
    ("p", "Giai đoạn kết thúc gồm đánh giá mức độ hoàn thành theo ma trận truy vết, rà soát bảo mật, đánh giá tính tái lập được, rồi thiết lập baseline cấu hình. Giai đoạn này cũng ghi nhận rõ những gì không thể hoàn thành và lý do."),

    ("h3", "1.3.4. Sản phẩm bàn giao của từng giai đoạn"),
    ("p", "Bảng 1.10 trình bày sản phẩm bàn giao của từng giai đoạn cùng nơi lưu giữ. Cột nơi lưu giữ quan trọng vì nó quyết định sản phẩm có thực sự tồn tại hay chỉ được tuyên bố."),
    ("tbl", "Bảng 1.10. Sản phẩm bàn giao theo giai đoạn",
     ["Giai đoạn", "Sản phẩm bàn giao", "Nơi lưu giữ"],
     [
        ["Lập kế hoạch", "Kế hoạch chất lượng, sổ rủi ro, ma trận truy vết", "docs/project-management/"],
        ["Thực hiện", "Mã nguồn ba thành phần, 9 migration CSDL", "backend/, android/, admin-web/"],
        ["Kiểm soát", "5 bộ kiểm thử, tệp kết quả CSV", "tests/, tests/results/"],
        ["Kết thúc", "Baseline cấu hình, tài liệu, thẻ phát hành", "docs/, thẻ Git"],
     ], [2.5, 6.0, 6.5]),

    ("h3", "1.3.5. Tiêu chí hoàn thành"),
    ("p", "Tiêu chí hoàn thành của dự án gồm bảy tiêu chí, mỗi tiêu chí gắn với một lệnh kiểm chứng cụ thể. Nguyên tắc này phù hợp với tinh thần tiêu chuẩn xác minh kiểm chứng: xác minh cung cấp bằng chứng khách quan rằng sản phẩm đáp ứng yêu cầu, còn xác nhận cung cấp bằng chứng rằng sản phẩm giải quyết đúng vấn đề cần giải quyết [5]. Bảng 1.11 trình bày các tiêu chí cùng cách kiểm chứng."),
    ("tbl", "Bảng 1.11. Tiêu chí hoàn thành và cách kiểm chứng",
     ["Mã", "Tiêu chí", "Lệnh kiểm chứng", "Kết quả"],
     [
        ["TC-1", "Backend biên dịch và kiểm thử đạt", "mvn verify", "113 kiểm thu, 0 lỗi"],
        ["TC-2", "Ứng dụng di động biên dịch và kiểm thử đạt", "gradlew testDebugUnitTest", "10 kiểm thu, 0 lỗi"],
        ["TC-3", "Bảng quản trị đóng gói sạch", "npm run build", "Không lỗi kiểu"],
        ["TC-4", "Hợp đồng API khớp", "tests/admin-web-contract.ps1", "102/102"],
        ["TC-5", "Kịch bản E2E đạt", "tests/e2e-api-tests.ps1", "160/160"],
        ["TC-6", "Stack triển khai khỏe", "docker compose ps", "3/3 healthy"],
        ["TC-7", "Không có bí mật trong kho mã nguồn", "Quét trước khi ghi", "0 bí mật"],
      ], [1.5, 5.0, 4.5, 4.0]),
    ("p", "Cần phân biệt hai cấp tiêu chí khác nhau, vì cách đếm của chúng không liên quan đến nhau và trộn lẫn hai cấp sẽ gây hiểu sai. Cấp thứ nhất là tiêu chí hoàn thành tại bảng 1.11: bảy tiêu chí ở cấp dự án, mỗi tiêu chí là một câu lệnh trả về mã thành công hoặc mã thất bại, và tiêu chí đạt khi lệnh đó chạy đúng. Cấp thứ hai là tiêu chí nghiệm thu ở cấp yêu cầu: mỗi dòng của ma trận truy vết mang một trạng thái riêng, và nghiệm thu xảy ra khi từng yêu cầu được gắn với bằng chứng. Bảy tiêu chí ở bảng 1.11 vì vậy không phải là tiêu chí nghiệm thu của bảy yêu cầu nào cả; chúng là cổng kiểm soát cho sản phẩm nói chung, trong khi kết quả nghiệm thu được đếm trên ma trận gồm 164 dòng và được trình bày tại bảng 1.17."),

    ("h2", "1.4. Ước lượng nỗ lực và thời gian biểu"),

    ("h3", "1.4.1. Cơ sở ước lượng"),
    ("p", "Ước lượng nỗ lực cần dựa trên cơ sở dữ liệu đo được. Trong dự án này, cơ sở đó không tồn tại. Quản lý phiên bản chỉ được thiết lập sau giai đoạn phát triển chính, và lịch sử phát triển trước đó không được ghi lại ở đâu. Hệ quả là không có dữ liệu về số giờ làm việc, số người tham gia, tốc độ hoàn thành hay lịch trình thực tế."),
    ("p", "Việc thiếu dữ liệu này có hệ quả trực tiếp lên độ tin cậy của mọi con số ước lượng. Theo mô hình COCOMO II, chi phí ước lượng được suy ra từ kích thước sản phẩm đo được, điều kiện phát triển và độ phức tạp nền tảng, với mô hình được hiệu chuẩn trên 161 điểm dữ liệu dự án [3]. Khi không có dữ liệu quan sát, kết quả ước lượng sẽ phản ánh giả định của người lập mô hình chứ không phản ánh dự án thực."),

    ("h3", "1.4.2. Phương pháp ước lượng được cân nhắc"),
    ("p", "Dự án cân nhắc hai phương pháp và ghi nhận lý do không áp dụng được. Phương pháp thứ nhất là COCOMO II, với ưu điểm là có cơ sở hiệu chuẩn thống kê và ba mô hình con tăng dần độ chính xác [3]. Phương pháp thứ hai là ước lượng tương đối so với dự án tương tự, với ưu điểm là phản ánh bối cảnh cụ thể hơn."),
    ("p", "Cả hai phương pháp đều không cho kết quả đáng tin cậy trong trường hợp này. Lý do chung là chúng đều giả định có dữ liệu tham chiếu mà dự án không có: COCOMO II cần đo kích thước sản phẩm và điều kiện phát triển trong thời gian thực hiện, còn ước lượng tương đối cần dữ liệu từ dự án tương tự cùng điều kiện. Dự án ghi nhận phương pháp phù hợp về nguyên tắc và sẽ áp dụng được nếu có dữ liệu, đồng thời từ chối đưa ra con số ước lượng ở thời điểm hiện tại."),

    ("h3", "1.4.3. Kế hoạch thời gian"),
    ("p", "Không có kế hoạch thời gian được ghi nhận và không thể tái tạo. Báo cáo này không đưa ra biểu đồ tiến độ hay thời gian biểu, vì cả hai đều đòi hỏi dữ liệu lịch sử không tồn tại. Mọi biểu đồ tiến độ được tạo ra trong trường hợp này sẽ là hình vẽ minh hoạ một sự thật không có, mà điều đó vi phạm nguyên tắc bằng chứng áp dụng cho toàn bộ báo cáo."),

    ("h3", "1.4.4. Đánh giá dữ liệu thực tế"),
    ("p", "Dự án có dữ liệu thực tế cho một số đại lượng, nhưng không phải cho đại lượng thời gian. Bảng 1.12 phân biệt rõ hai nhóm này. Nhóm có số liệu bao gồm quy mô mã nguồn, số kiểm thử, số bảng dữ liệu và số tài liệu; tất cả đều đếm được bằng lệnh. Nhóm không có số liệu bao gồm thời gian phát triển, nỗ lực, quy mô nhóm và tiến độ."),
    ("tbl", "Bảng 1.12. Phân loại dữ liệu dự án theo khả năng kiểm chứng",
     ["Đại lượng", "Giá trị", "Cách xác minh", "Trạng thái"],
     [
        ["Số tệp mã nguồn Java", "78", "Đếm tệp trong backend/src/main/java", "Đo được"],
        ["Số tệp mã nguồn Kotlin", "22", "Đếm tệp trong android/app/src/main/java", "Đo được"],
        ["Số tệp TypeScript", "13", "Đếm tệp trong admin-web/src", "Đo được"],
        ["Số kiểm tra tự động", "385", "Tổng từ 5 bộ kiểm thử", "Đo được"],
        ["Số bảng dữ liệu", "11", "Truy vấn information_schema", "Đo được"],
        ["Số tệp tài liệu", "28", "Đếm tệp trong docs/", "Đo được"],
        ["Thời gian phát triển", "—", "Không có bản ghi", "Không đo được"],
        ["Tổng nỗ lực", "—", "Không có bản ghi", "Không đo được"],
        ["Số người tham gia", "—", "Không có bản ghi", "Không đo được"],
        ["Tốc độ hoàn thành", "—", "Không có bản ghi", "Không đo được"],
     ], [3.5, 2.0, 6.0, 3.5]),

    ("h3", "1.4.5. Hạn chế của dữ liệu nỗ lực và lịch trình"),
    ("p", "Khoảng trống dữ liệu lịch sử có một đặc điểm quan trọng: nó vĩnh viễn. Dữ liệu không được ghi lại tại thời điểm nó tồn tại sẽ không thể tái tạo sau này bằng bất kỳ phương pháp nào. Quản lý phiên bản hiện có chỉ ghi nhận trạng thái từ thời điểm baseline trở đi, và không thể cung cấp thông tin về quá trình trước đó."),
    ("p", "Hệ quả này được đánh giá là bài học quan trọng nhất của dự án về quản lý dự án, và được trình bày tại mục 3.5.4. Ở đây cần nhấn mạnh rằng đây không phải khuyến nghị chung chung mà là hệ quả cụ thể đã xảy ra: dự án có thể chứng minh chất lượng sản phẩm bằng 385 kiểm tra tự động, nhưng không thể chứng minh được dự án được quản lý tốt về mặt tiến độ và nỗ lực, vì dữ liệu cho việc đó không tồn tại."),
    ("p", "Để giảm thiểu rủi ro này trong các dự án tương lai, ba biện pháp đáng chú ý là: khởi tạo kho quản lý phiên bản từ ngày đầu tiên của dự án; ghi nhận cam kết và quyết định trong mô tả thay đổi; và cập nhật sổ rủi ro theo chu kỳ thay vì ở giai đoạn cuối. Ba biện pháp này đều có chi phí gần như bằng không nếu thực hiện sớm, nhưng không thể khôi phục nếu bỏ qua."),

    ("h2", "1.5. Lập kế hoạch chất lượng"),
]
